name: Testing actions on AdamAi
run-name: ${{ github.actor }} is running action in AdamAi
on: [push]
jobs:
  My_Actions:
   runs-on: ubuntu-latest
   steps:
    - uses: action/checkout@v3
    - run: echo "This is running on ${{ runner.os}}"
    - run: echo "It was triggered by ${{github.event_name}} "
    - run: echo " ${{github.repository}} is on ${{github.ref}} branch"
    - name: Just random
      run: echo "Good day"
